<?xml version='1.0' encoding='utf-8'?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="panda">
  <!-- safety_distance: Minimum safety distance in [m] by which the collision volumes are expanded and which is enforced during robot motions -->
  <!-- arm_id: Namespace of the panda arm. Serves to differentiate between arms in case of multiple instances. -->
  <xacro:macro name="panda_arm" params="arm_id:='panda' description_pkg:='franka_description' connected_to:='' xyz:='0 0 0' rpy:='0 0 0' safety_distance:=0">
    <xacro:unless value="${not connected_to}">
      <joint name="${arm_id}_joint_${connected_to}" type="fixed">
        <parent link="${connected_to}"/>
        <child link="${arm_id}_link0"/>
        <origin rpy="${rpy}" xyz="${xyz}"/>
      </joint>
    </xacro:unless>
    <link name="${arm_id}_link0">
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link0.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="-0.075 0 0.06" rpy="0 ${pi/2} 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.03" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="-0.06 0 0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="-0.09 0 0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="-0.041018 -0.00014 0.049974"/>
        <mass value="0.629769"/>
        <inertia ixx="0.00315" ixy="8.2904e-07" ixz="0.00015" iyy="0.00388" iyz="8.2299e-06" izz="0.004285"/>
      </inertial>
    </link>
    <link name="${arm_id}_link1">
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link1.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.1915" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.2830" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.333" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.05" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0.003875 0.002081 -0.04762"/>
        <mass value="4.970684"/>
        <inertia ixx="0.70337" ixy="-0.000139" ixz="0.006772" iyy="0.70661" iyz="0.019169" izz="0.009117"/>
      </inertial>
    </link>
    <joint name="${arm_id}_joint1" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.8973" soft_upper_limit="2.8973"/>
      <origin rpy="0 0 0" xyz="0 0 0.333"/>
      <parent link="${arm_id}_link0"/>
      <child link="${arm_id}_link1"/>
      <axis xyz="0 0 1"/>
      <limit effort="87" lower="-2.8973" upper="2.8973" velocity="2.1750"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="${arm_id}_link2">
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link2.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.12" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="-0.003141 -0.02872  0.003495"/>
        <mass value="0.646926"/>
        <inertia ixx="0.007962" ixy="-0.003925" ixz="0.010254" iyy="0.02811" iyz="0.000704" izz="0.025995"/>
      </inertial>
    </link>
    <joint name="${arm_id}_joint2" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-1.7628" soft_upper_limit="1.7628"/>
      <origin rpy="${-pi/2} 0 0" xyz="0 0 0"/>
      <parent link="${arm_id}_link1"/>
      <child link="${arm_id}_link2"/>
      <axis xyz="0 0 1"/>
      <limit effort="87" lower="-1.7628" upper="1.7628" velocity="2.1750"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="${arm_id}_link3">
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link3.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.145" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.15" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.22" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.07" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="2.7518e-02 3.9252e-02 -6.6502e-02"/>
        <mass value="3.228604"/>
        <inertia ixx="0.037242" ixy="-0.004761" ixz="-0.011396" iyy="0.036155" iyz="-0.012805" izz="0.01083"/>
      </inertial>
    </link>
    <joint name="${arm_id}_joint3" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.8973" soft_upper_limit="2.8973"/>
      <origin rpy="${pi/2} 0 0" xyz="0 -0.316 0"/>
      <parent link="${arm_id}_link2"/>
      <child link="${arm_id}_link3"/>
      <axis xyz="0 0 1"/>
      <limit effort="87" lower="-2.8973" upper="2.8973" velocity="2.1750"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="${arm_id}_link4">
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link4.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.12" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="-5.317e-02 1.04419e-01 2.7454e-02"/>
        <mass value="3.587895"/>
        <inertia ixx="0.025853" ixy="0.007796" ixz="-0.001332" iyy="0.019552" iyz="0.008641" izz="0.028323"/>
      </inertial>
    </link>
    <joint name="${arm_id}_joint4" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-3.0718" soft_upper_limit="-0.0698"/>
      <origin rpy="${pi/2} 0 0" xyz="0.0825 0 0"/>
      <parent link="${arm_id}_link3"/>
      <child link="${arm_id}_link4"/>
      <axis xyz="0 0 1"/>
      <limit effort="87" lower="-3.0718" upper="-0.0698" velocity="2.1750"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="${arm_id}_link5">
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link5.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.26" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.06+safety_distance}" length="0.1" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.31" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.21" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.06+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.08 -0.13" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.025+safety_distance}" length="0.14" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.08 -0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.025+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0.08 -0.20" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.025+safety_distance}" />
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="-1.1953e-02 4.1065e-02 -3.8437e-02"/>
        <mass value="1.225946"/>
        <inertia ixx="0.035549" ixy="-0.002117" ixz="-0.004037" iyy="0.029474" iyz="0.000229" izz="0.008627"/>
      </inertial>
    </link>
    <joint name="${arm_id}_joint5" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.8973" soft_upper_limit="2.8973"/>
      <origin rpy="${-pi/2} 0 0" xyz="-0.0825 0.384 0"/>
      <parent link="${arm_id}_link4"/>
      <child link="${arm_id}_link5"/>
      <axis xyz="0 0 1"/>
      <limit effort="12" lower="-2.8973" upper="2.8973" velocity="2.6100"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="${arm_id}_link6">
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link6.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 -0.03" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.05+safety_distance}" length="0.08" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 0.01" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.05+safety_distance}" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.07" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.05+safety_distance}" />
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="6.0149e-02 -1.4117e-02 -1.0517e-02"/>
        <mass value="1.666555"/>
        <inertia ixx="0.001964" ixy="0.000109" ixz="-0.001158" iyy="0.004354" iyz="0.000341" izz="0.005433"/>
      </inertial>
    </link>
    <joint name="${arm_id}_joint6" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-0.0175" soft_upper_limit="3.7525"/>
      <origin rpy="${pi/2} 0 0" xyz="0 0 0"/>
      <parent link="${arm_id}_link5"/>
      <child link="${arm_id}_link6"/>
      <axis xyz="0 0 1"/>
      <limit effort="12" lower="-0.0175" upper="3.7525" velocity="2.6100"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="${arm_id}_link7">
      <visual>
        <geometry>
          <mesh filename="package://${description_pkg}/meshes/visual/link7.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0.01" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${0.04+safety_distance}" length="0.14" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 0.08" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.04+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 -0.06" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.04+safety_distance}"  />
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="1.0517e-02 -4.252e-03 6.1597e-02"/>
        <mass value="0.735522"/>
        <inertia ixx="0.012516" ixy="-0.000428" ixz="-0.001196" iyy="0.010027" iyz="-0.000741" izz="0.004815"/>
      </inertial>
    </link>
    <joint name="${arm_id}_joint7" type="revolute">
      <safety_controller k_position="100.0" k_velocity="40.0" soft_lower_limit="-2.8973" soft_upper_limit="2.8973"/>
      <origin rpy="${pi/2} 0 0" xyz="0.088 0 0"/>
      <parent link="${arm_id}_link6"/>
      <child link="${arm_id}_link7"/>
      <axis xyz="0 0 1"/>
      <limit effort="12" lower="-2.8973" upper="2.8973" velocity="2.6100"/>
      <dynamics damping="0.0" friction="0.0"/>
    </joint>
    <link name="${arm_id}_link8">
      <collision>
        <origin xyz="0.0424 0.0424 -0.0250" rpy="${pi} ${pi/2} ${pi/2}"/>
        <geometry>
          <cylinder radius="${0.03+safety_distance}"  length="0.01" />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.0424 0.0424 -0.02" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.03+safety_distance}"  />
        </geometry>
      </collision>
      <collision>
        <origin xyz="0.0424 0.0424 -0.03" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${0.03+safety_distance}"  />
        </geometry>
      </collision>
      <inertial>
        <mass value="0"/>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <inertia ixx="0" ixy="0" ixz="0" iyy="0" iyz="0" izz="0"/>
      </inertial>
    </link>
    <joint name="${arm_id}_joint8" type="fixed">
      <origin rpy="0 0 0" xyz="0 0 0.107"/>
      <parent link="${arm_id}_link7"/>
      <child link="${arm_id}_link8"/>
    </joint>
  </xacro:macro>
</robot>
